M48
; DRILL file {KiCad 7.0.9} date Thursday, September 19, 2024 at 11:25:19 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-19T11:25:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.0787Y-2.0866
X0.3937Y-0.0787
X0.7087Y-2.0866
T0
M30
